language: node_js
node_js:
  - "10"
install: make npm_install
matrix:
  include:
    - name: "Node Unit Tests"
      install: make npm_install_node
      script: make test
    - name: "Selenium Unit Tests"
      addons:
        chrome: stable
      before_install:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      install: make npm_install_selenium
      script: make selenium_test
